# Dev profile overrides

spring:
  config:
    import: optional:/svc/nte/config/nte-config-dev.yml

management:
  endpoints:
    web:
      exposure:
        include: health,info,quartz
  endpoint:
    health:
      show-details: always

bot:
  telegram:
    channel-names: NFTReally.Dev.BackEnd
