#------------------------------------------------
# server setting
#------------------------------------------------
server:
  port: 8080

#------------------------------------------------
# spring setting
#------------------------------------------------
spring:
  application:
    name: message-sending-api-server
  output:
    ansi:
      enabled: always
  #----------------------------------------------
  # spring-quartz
  #----------------------------------------------
  quartz:
    scheduler-name: email-sending-scheduler
    job-store-type: memory
    overwrite-existing-jobs: false
    startup-delay: 5
    wait-for-jobs-to-complete-on-shutdown: true
    auto-startup: true

#------------------------------------------------
# aws ses
#------------------------------------------------
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA2F6HCY2MG5U5QYHM
      secret-key: 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

#------------------------------------------------
# actuator
#------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    quartz:
      enabled: true

#------------------------------------------------
# logging
#------------------------------------------------
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.msas.ses: DEBUG