#################################################
# server setting
#################################################
server:
  port: 7092

#################################################
# logging
#################################################
logging:
  config: classpath:logback/logback-${spring.config.activate.on-profile}.xml
#  level:
#    root: ERROR
#    org.springframework.web: INFO
#    org.quartz: DEBUG
#    com.msas: DEBUG

#################################################
# spring setting
#################################################
spring:
  config:
    activate:
      on-profile: dev58
  application:
    #__________________________________________________________________
    # application name for NFTReally : ntc:7091, nte:7092, nts:7093
    #__________________________________________________________________
    name: NTE
  output:
    ansi:
      enabled: always
  #################################################
  # spring-quartz
  #################################################
  quartz:
    scheduler-name: email-sending-scheduler
    overwrite-existing-jobs: false
    startup-delay: 10
    wait-for-jobs-to-complete-on-shutdown: true
    auto-startup: true

    #__________________________________________________________________
    # 쿼츠 프로퍼티로 직접 주입해야 설정이 된다.
    # 레퍼런스나 참조 문서가 없는 상태에서 어렵게 찾아낸 방법이므로 두번 고생하지 말자.
    # spring.quartz.* 는 실제 쿼츠에 설정이 안먹는다.
    #__________________________________________________________________
    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 10

      #_________________________________________________________________________________________________
      # (!) RAMStore 사용시 이후 설정 모두 주석 처리
      # Quartz Configuration: https://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/
      # RAMJobStore -> org.quartz.jobStore.class: org.quartz.simpl.RAMJobStore
      #_________________________________________________________________________________________________

      # Database Store
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.dataSource.quartzDataSource.provider: hikaricp
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.dataSource: quartzDataSource
      #
      org.quartz.dataSource.quartzDataSource.driver: org.mariadb.jdbc.Driver
      org.quartz.dataSource.quartzDataSource.URL: jdbc:mariadb://58.232.131.21:3306/quartz
      org.quartz.dataSource.quartzDataSource.user: quartz
      org.quartz.dataSource.quartzDataSource.password: quartz
      #
      org.quartz.dataSource.quartzDataSource.maximumPoolSize: 10
      org.quartz.dataSource.quartzDataSource.connectionTestQuery: SELECT 1
      org.quartz.dataSource.quartzDataSource.validationTimeout: 5000
      org.quartz.dataSource.quartzDataSource.idleTimeout: 0

      # Logging Trigger History
      # https://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigPlugins.html
      org.quartz.plugin.triggHistory.class: org.quartz.plugins.history.LoggingTriggerHistoryPlugin
      org.quartz.plugin.triggHistory.triggerFiredMessage: '🔥Trigger {1}.{0} fired job {6}.{5} at: {4, date, HH:mm:ss MM/dd/yyyy}'
      org.quartz.plugin.triggHistory.triggerCompleteMessage: '🔥Trigger {1}.{0} completed firing job {6}.{5} at {4, date, HH:mm:ss MM/dd/yyyy\}.'

  #################################################
  # database
  #################################################
  datasource:
    name: NFTReally-Database
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://58.232.131.21:3306/nft
    username: quartz
    password: quartz

#################################################
# AWS {SES, DynamoDB}
#################################################
aws:
  dynamo:
    region: ap-northeast-2
    access-key: AKIA2F6HCY2MNDRHU6BX
    secret-key: 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
  ses:
    region: ap-northeast-2
    access-key: AKIA2F6HCY2MNDRHU6BX
    secret-key: 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

#################################################
# actuator
#################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    quartz:
      enabled: true

#################################################
# bot
#################################################
bot:
  telegram:
    token-id: 5710353844:AAEqVlaqAa7-Ixv-hnximDy8xa_BkkepRV8
    channel-names: NFTReally.Notification, NFTReally.BackEnd

#################################################
# polling checker
#################################################
polling:
  schedule:
      send-email-check-time: 60000
      send-email-event-check-time: 60000

#################################################
# mybatis mapper
#################################################
mybatis:
  mapper-locations: classpath:mybatis/*.xml
