#------------------------------------------------
# server setting
#------------------------------------------------
server:
  port: 8080

#------------------------------------------------
# spring setting
#------------------------------------------------
spring:
  application:
    name: message-sending-api-server
  output:
    ansi:
      enabled: always
  #----------------------------------------------
  # spring-quartz
  #----------------------------------------------
  quartz:
    scheduler-name: email-sending-scheduler
    overwrite-existing-jobs: false
    startup-delay: 10
    wait-for-jobs-to-complete-on-shutdown: true
    auto-startup: true

    #############################################
    # 쿼츠 프로퍼티로 직접 주입해야 설정이 된다.
    # 레퍼런스나 참조 문서가 없는 상태에서 어렵게 찾아낸 방법이므로 두번 고생하지 말자.
    # spring.quartz.* 는 실제 쿼츠에 설정이 안먹는다.
    #############################################
    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 30

      # Quartz Configuration: https://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/
      org.quartz.dataSource.quartzDataSource.provider: hikaricp
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.dataSource: quartzDataSource
      org.quartz.dataSource.quartzDataSource.driver: org.mariadb.jdbc.Driver

      org.quartz.dataSource.quartzDataSource.URL: jdbc:mariadb://58.232.131.21:3306/quartz #test: jdbc:mariadb://58.232.131.21:3306/quartz
      org.quartz.dataSource.quartzDataSource.user: quartz
      org.quartz.dataSource.quartzDataSource.password: quartz

#------------------------------------------------
# aws ses
#------------------------------------------------
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA2F6HCY2MNDRHU6BX
      secret-key: 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

#------------------------------------------------
# actuator
#------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    quartz:
      enabled: true

#------------------------------------------------
# logging
#------------------------------------------------
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.msas.ses: DEBUG

#------------------------------------------------
# bot
#------------------------------------------------
bot:
  telegram:
    token-id: 5710353844:AAEqVlaqAa7-Ixv-hnximDy8xa_BkkepRV8
    channel-names: NFTReally.Notification, NFTReally.BackEnd
