spring:
  application:
    name: message sending api server

#---------------------------------------------------------------

server:
  port: 8080

#---------------------------------------------------------------
# aws ses
#---------------------------------------------------------------
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA2F6HCY2MG5U5QYHM
      secret-key: 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
    ses:
      sender: no-reply@nftreally.io

#---------------------------------------------------------------
# actuator
#---------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"

#---------------------------------------------------------------
# logging
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.msas.ses: DEBUG

#---------------------------------------------------------------