-- =============================================
-- Joins EMS - 전체 스키마 초기화
-- PostgreSQL 17
-- =============================================

-- =============================================
-- 1. Email Tables
-- =============================================

CREATE TABLE IF NOT EXISTS ADM_EMAIL_SEND_MST (
    EMAIL_SEND_SEQ       BIGSERIAL    PRIMARY KEY,
    EMAIL_TYP_CD         VARCHAR(10)  NULL,
    EMAIL_CLS_CD         VARCHAR(10)  NULL,
    SEND_DIV_CD          VARCHAR(10)  NULL,
    RSV_SEND_DT          TIMESTAMP    NULL,
    TENANT_ID            VARCHAR(36)  DEFAULT 'default',
    STM_FIR_REG_DT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_FIR_REG_USER_ID  VARCHAR(50)  NULL,
    STM_LAST_UPD_DT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_LAST_UPD_USER_ID VARCHAR(50)  NULL
);

COMMENT ON COLUMN ADM_EMAIL_SEND_MST.EMAIL_TYP_CD         IS '이메일 유형 코드';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.EMAIL_CLS_CD         IS '이메일 분류 코드';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.SEND_DIV_CD          IS '발송 구분 코드 (T:텍스트, H:HTML, P:템플릿)';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.RSV_SEND_DT          IS '예약 발송 일시';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.TENANT_ID            IS '테넌트 ID';

CREATE TABLE IF NOT EXISTS ADM_EMAIL_SEND_DTL (
    EMAIL_SEND_DTL_SEQ   BIGSERIAL    PRIMARY KEY,
    EMAIL_SEND_SEQ       BIGINT       NOT NULL,
    SEND_STS_CD          VARCHAR(10)  DEFAULT 'SR',
    SEND_RSLT_TYP_CD     VARCHAR(10)  NULL,
    RCV_EMAIL_ADDR       VARCHAR(255) NULL,
    SEND_EMAIL_ADDR      VARCHAR(255) NULL,
    EMAIL_TITLE          VARCHAR(500) NULL,
    EMAIL_CTS            TEXT         NULL,
    EMAIL_TMPLET_ID      VARCHAR(100) NULL,
    CORRELATION_ID       VARCHAR(36)  NULL,
    SES_MSG_ID           VARCHAR(255) NULL,
    SES_REAL_SEND_DT     TIMESTAMP    NULL,
    TENANT_ID            VARCHAR(36)  DEFAULT 'default',
    STM_FIR_REG_DT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_FIR_REG_USER_ID  VARCHAR(50)  NULL,
    STM_LAST_UPD_DT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_LAST_UPD_USER_ID VARCHAR(50)  NULL,
    FOREIGN KEY (EMAIL_SEND_SEQ) REFERENCES ADM_EMAIL_SEND_MST(EMAIL_SEND_SEQ)
);

CREATE INDEX IF NOT EXISTS IDX_DTL_SEND_SEQ      ON ADM_EMAIL_SEND_DTL (EMAIL_SEND_SEQ);
CREATE INDEX IF NOT EXISTS IDX_DTL_STS_CD        ON ADM_EMAIL_SEND_DTL (SEND_STS_CD);
CREATE INDEX IF NOT EXISTS IDX_DTL_SES_MSG_ID    ON ADM_EMAIL_SEND_DTL (SES_MSG_ID);
CREATE INDEX IF NOT EXISTS IDX_DTL_CORRELATION   ON ADM_EMAIL_SEND_DTL (CORRELATION_ID);

CREATE TABLE IF NOT EXISTS ADM_EMAIL_ATTCH_FILE_LST (
    EMAIL_ATTACH_FILE_SEQ BIGSERIAL    PRIMARY KEY,
    EMAIL_SEND_DTL_SEQ    BIGINT       NOT NULL,
    FILE_PATH             VARCHAR(500) NULL,
    FILE_NM               VARCHAR(255) NULL,
    ORGN_FILE_NM          VARCHAR(255) NULL,
    FILE_SZ               BIGINT       NULL,
    FOREIGN KEY (EMAIL_SEND_DTL_SEQ) REFERENCES ADM_EMAIL_SEND_DTL(EMAIL_SEND_DTL_SEQ)
);

-- =============================================
-- 2. Blacklist Table
-- =============================================

CREATE TABLE IF NOT EXISTS ADM_EMAIL_BL_MST (
    EMAIL_BL_SEQ          BIGSERIAL    PRIMARY KEY,
    EMAIL_ADDR            VARCHAR(255) NOT NULL,
    EMAIL_CUTOFF_TYP_CD   VARCHAR(10)  NULL,
    TENANT_ID             VARCHAR(36)  NULL,
    REASON                VARCHAR(50)  NULL,
    STM_FIR_REG_DT        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_FIR_REG_USER_ID   VARCHAR(50)  NULL,
    STM_LAST_UPD_DT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_LAST_UPD_USER_ID  VARCHAR(50)  NULL,
    UNIQUE (EMAIL_ADDR)
);

COMMENT ON COLUMN ADM_EMAIL_BL_MST.EMAIL_ADDR          IS '차단 이메일 주소';
COMMENT ON COLUMN ADM_EMAIL_BL_MST.EMAIL_CUTOFF_TYP_CD IS '차단 유형 코드';
COMMENT ON COLUMN ADM_EMAIL_BL_MST.TENANT_ID           IS '테넌트 ID';
COMMENT ON COLUMN ADM_EMAIL_BL_MST.REASON              IS '차단 사유 (BOUNCE/COMPLAINT)';

-- =============================================
-- 3. Tenant Registry
-- =============================================

CREATE TABLE IF NOT EXISTS TENANT_REGISTRY (
    TENANT_ID            VARCHAR(36)  PRIMARY KEY,
    TENANT_NAME          VARCHAR(100) NOT NULL,
    SES_TENANT_NAME      VARCHAR(100) NULL,
    DOMAIN               VARCHAR(255) NOT NULL,
    API_KEY              VARCHAR(128) NOT NULL,
    CONFIG_SET_NAME      VARCHAR(100) NULL,
    VERIFICATION_STATUS  VARCHAR(20)  DEFAULT 'PENDING',
    QUOTA_DAILY          INT          DEFAULT 10000,
    QUOTA_MONTHLY        INT          DEFAULT 300000,
    STATUS               VARCHAR(20)  DEFAULT 'INACTIVE',
    CREATED_AT           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (DOMAIN),
    UNIQUE (API_KEY)
);

COMMENT ON COLUMN TENANT_REGISTRY.TENANT_NAME         IS '고객사 이름';
COMMENT ON COLUMN TENANT_REGISTRY.SES_TENANT_NAME     IS 'SES 테넌트 내부 명칭';
COMMENT ON COLUMN TENANT_REGISTRY.DOMAIN              IS '발송 도메인';
COMMENT ON COLUMN TENANT_REGISTRY.API_KEY             IS '테넌트별 API Key';
COMMENT ON COLUMN TENANT_REGISTRY.CONFIG_SET_NAME     IS 'SES Configuration Set 이름';
COMMENT ON COLUMN TENANT_REGISTRY.VERIFICATION_STATUS IS '도메인 인증 상태';
COMMENT ON COLUMN TENANT_REGISTRY.QUOTA_DAILY         IS '일일 발송 한도';
COMMENT ON COLUMN TENANT_REGISTRY.QUOTA_MONTHLY       IS '월간 발송 한도';
COMMENT ON COLUMN TENANT_REGISTRY.STATUS              IS '테넌트 상태';

CREATE INDEX IF NOT EXISTS IDX_TENANT_STATUS ON TENANT_REGISTRY (STATUS);

-- =============================================
-- 4. Tenant Sender
-- =============================================

CREATE TABLE IF NOT EXISTS TENANT_SENDER (
    ID         BIGSERIAL PRIMARY KEY,
    TENANT_ID  VARCHAR(36) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(100),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (TENANT_ID, EMAIL)
);

CREATE INDEX IF NOT EXISTS IDX_SENDER_TENANT ON TENANT_SENDER (TENANT_ID);

-- =============================================
-- 5. Suppression List (테넌트별 수신거부)
-- =============================================

CREATE TABLE IF NOT EXISTS SUPPRESSION_LIST (
    ID BIGSERIAL PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    REASON VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (TENANT_ID, EMAIL)
);

CREATE INDEX IF NOT EXISTS IDX_SUPP_TENANT ON SUPPRESSION_LIST (TENANT_ID);

-- =============================================
-- 6. System Config
-- =============================================

CREATE TABLE IF NOT EXISTS SYSTEM_CONFIG (
    CONFIG_KEY   VARCHAR(100) PRIMARY KEY,
    CONFIG_VALUE TEXT,
    DESCRIPTION  VARCHAR(500),
    ENCRYPTED    BOOLEAN DEFAULT FALSE,
    UPDATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 기본 설정값 (v2 경로)
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, ENCRYPTED) VALUES
('gateway.endpoint', '', 'API Gateway Base URL', FALSE),
('gateway.region', 'ap-northeast-2', 'API Gateway AWS 리전', FALSE),
('gateway.api-key', '', 'API Gateway API Key', TRUE),
('gateway.send-path', '/email-enqueue', '이메일 발송 큐 등록 경로', FALSE),
('gateway.results-path', '/event-query', '발송 결과 조회 경로', FALSE),
('gateway.config-path', '/tenant-setup', '테넌트 설정 경로', FALSE),
('gateway.tenant-setup-path', '/tenant-setup', '테넌트 온보딩 경로', FALSE),
('delivery.polling-interval', '120000', '보정 폴링 주기 (ms, 기본 2분)', FALSE)
ON CONFLICT (CONFIG_KEY) DO NOTHING;

-- =============================================
-- 7. Email Send Batch (예약 발송)
-- =============================================

CREATE TABLE IF NOT EXISTS ADM_EMAIL_SEND_BATCH (
    BATCH_ID       VARCHAR(36) PRIMARY KEY,
    TEMPLATE_NAME  VARCHAR(255),
    FROM_ADDR      VARCHAR(255),
    TAGS           TEXT,
    JOB_NAME       VARCHAR(255),
    JOB_GROUP      VARCHAR(255),
    DESCRIPTION    TEXT,
    START_DATE_AT  TIMESTAMP,
    STATUS         VARCHAR(30) DEFAULT 'PENDING',
    TOTAL_COUNT    INT DEFAULT 0,
    TENANT_ID      VARCHAR(50),
    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ADM_EMAIL_SEND_BATCH_ITEM (
    ITEM_ID              BIGSERIAL PRIMARY KEY,
    BATCH_ID             VARCHAR(36) NOT NULL,
    ITEM_INDEX           INT NOT NULL,
    CORRELATION_ID       VARCHAR(36),
    EMAIL_SEND_DTL_SEQ   INT,
    TO_ADDRS             TEXT NOT NULL,
    CC_ADDRS             TEXT,
    BCC_ADDRS            TEXT,
    TEMPLATE_PARAMETERS  TEXT,
    CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ADM_BATCH FOREIGN KEY (BATCH_ID) REFERENCES ADM_EMAIL_SEND_BATCH(BATCH_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_ADM_BATCH_ITEM_BATCH ON ADM_EMAIL_SEND_BATCH_ITEM(BATCH_ID, ITEM_INDEX);

-- =============================================
-- 8. Template-Tenant Mapping
-- =============================================

CREATE TABLE IF NOT EXISTS ADM_TEMPLATE_TENANT_MAP (
    MAP_SEQ          BIGSERIAL PRIMARY KEY,
    TEMPLATE_NAME    VARCHAR(255) NOT NULL,
    TENANT_ID        VARCHAR(100) NOT NULL,
    SUBJECT          TEXT,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_TEMPLATE_TENANT UNIQUE (TEMPLATE_NAME, TENANT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_TEMPLATE_TENANT_NAME ON ADM_TEMPLATE_TENANT_MAP (TEMPLATE_NAME);
CREATE INDEX IF NOT EXISTS IDX_TEMPLATE_TENANT_ID ON ADM_TEMPLATE_TENANT_MAP (TENANT_ID);

-- =============================================
-- 9. Email Event Log
-- =============================================

CREATE TABLE IF NOT EXISTS ADM_EMAIL_EVENT_LOG (
    EVENT_LOG_SEQ    BIGSERIAL    PRIMARY KEY,
    CORRELATION_ID   VARCHAR(36)  NULL,
    SES_MESSAGE_ID   VARCHAR(255) NULL,
    EVENT_TYPE       VARCHAR(30)  NOT NULL,
    EVENT_DETAIL     TEXT         NULL,
    TENANT_ID        VARCHAR(36)  NULL,
    CREATED_AT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_EVENT_LOG_CORR ON ADM_EMAIL_EVENT_LOG (CORRELATION_ID);
CREATE INDEX IF NOT EXISTS IDX_EVENT_LOG_TYPE ON ADM_EMAIL_EVENT_LOG (EVENT_TYPE);

COMMENT ON TABLE ADM_EMAIL_EVENT_LOG IS 'SES 이벤트 이력 (Delivery, Bounce, Open, Click 등)';

-- =============================================
-- 10. Admin User (JWT 인증)
-- =============================================

CREATE TABLE IF NOT EXISTS ADM_USER_MST (
    USER_ID       BIGSERIAL    PRIMARY KEY,
    USERNAME      VARCHAR(50)  NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DISPLAY_NAME  VARCHAR(100) NULL,
    ROLE          VARCHAR(20)  DEFAULT 'ADMIN',
    IS_ACTIVE     BOOLEAN      DEFAULT TRUE,
    LAST_LOGIN_AT TIMESTAMP    NULL,
    CREATED_AT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ADM_USER_MST IS '관리자 계정 (JWT 인증)';

-- 초기 관리자 계정 (admin / admin, BCrypt 해시)
INSERT INTO ADM_USER_MST (USERNAME, PASSWORD_HASH, DISPLAY_NAME, ROLE)
VALUES ('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '관리자', 'ADMIN')
ON CONFLICT (USERNAME) DO NOTHING;
