-- =============================================
-- Email Tables
-- =============================================

CREATE TABLE IF NOT EXISTS ADM_EMAIL_SEND_MST (
    EMAIL_SEND_SEQ       BIGSERIAL    PRIMARY KEY,
    EMAIL_TYP_CD         VARCHAR(10)  NULL,
    EMAIL_CLS_CD         VARCHAR(10)  NULL,
    SEND_DIV_CD          VARCHAR(10)  NULL,
    RSV_SEND_DT          TIMESTAMP    NULL,
    TENANT_ID            VARCHAR(36)  DEFAULT 'default',
    STM_FIR_REG_DT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_FIR_REG_USER_ID  VARCHAR(50)  NULL,
    STM_LAST_UPD_DT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_LAST_UPD_USER_ID VARCHAR(50)  NULL
);

COMMENT ON COLUMN ADM_EMAIL_SEND_MST.EMAIL_TYP_CD         IS '이메일 유형 코드';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.EMAIL_CLS_CD         IS '이메일 분류 코드';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.SEND_DIV_CD          IS '발송 구분 코드 (T:텍스트, H:HTML, P:템플릿)';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.RSV_SEND_DT          IS '예약 발송 일시';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.TENANT_ID            IS '테넌트 ID';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.STM_FIR_REG_DT       IS '최초 등록 일시';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.STM_FIR_REG_USER_ID  IS '최초 등록자';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.STM_LAST_UPD_DT      IS '최종 수정 일시';
COMMENT ON COLUMN ADM_EMAIL_SEND_MST.STM_LAST_UPD_USER_ID IS '최종 수정자';

CREATE TABLE IF NOT EXISTS ADM_EMAIL_SEND_DTL (
    EMAIL_SEND_DTL_SEQ   BIGSERIAL    PRIMARY KEY,
    EMAIL_SEND_SEQ       BIGINT       NOT NULL,
    SEND_STS_CD          VARCHAR(10)  DEFAULT 'SR',
    SEND_RSLT_TYP_CD     VARCHAR(10)  NULL,
    RCV_EMAIL_ADDR       VARCHAR(255) NULL,
    SEND_EMAIL_ADDR      VARCHAR(255) NULL,
    EMAIL_TITLE          VARCHAR(500) NULL,
    EMAIL_CTS            TEXT         NULL,
    EMAIL_TMPLET_ID      VARCHAR(100) NULL,
    SES_MSG_ID           VARCHAR(255) NULL,
    SES_REAL_SEND_DT     TIMESTAMP    NULL,
    TENANT_ID            VARCHAR(36)  DEFAULT 'default',
    STM_FIR_REG_DT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_FIR_REG_USER_ID  VARCHAR(50)  NULL,
    STM_LAST_UPD_DT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_LAST_UPD_USER_ID VARCHAR(50)  NULL,
    FOREIGN KEY (EMAIL_SEND_SEQ) REFERENCES ADM_EMAIL_SEND_MST(EMAIL_SEND_SEQ)
);

COMMENT ON COLUMN ADM_EMAIL_SEND_DTL.EMAIL_SEND_SEQ       IS 'FK: ADM_EMAIL_SEND_MST';
COMMENT ON COLUMN ADM_EMAIL_SEND_DTL.SEND_STS_CD          IS '발송 상태 코드 (SR/SS/SE/SD/SB/SC/SF)';
COMMENT ON COLUMN ADM_EMAIL_SEND_DTL.SEND_RSLT_TYP_CD     IS '발송 결과 유형 코드';
COMMENT ON COLUMN ADM_EMAIL_SEND_DTL.RCV_EMAIL_ADDR       IS '수신 이메일 주소';
COMMENT ON COLUMN ADM_EMAIL_SEND_DTL.SEND_EMAIL_ADDR      IS '발신 이메일 주소';
COMMENT ON COLUMN ADM_EMAIL_SEND_DTL.EMAIL_TITLE          IS '이메일 제목';
COMMENT ON COLUMN ADM_EMAIL_SEND_DTL.EMAIL_CTS            IS '이메일 내용';
COMMENT ON COLUMN ADM_EMAIL_SEND_DTL.EMAIL_TMPLET_ID      IS '이메일 템플릿 ID';
COMMENT ON COLUMN ADM_EMAIL_SEND_DTL.SES_MSG_ID           IS 'AWS SES 메시지 ID';
COMMENT ON COLUMN ADM_EMAIL_SEND_DTL.SES_REAL_SEND_DT     IS 'SES 실제 발송 일시';
COMMENT ON COLUMN ADM_EMAIL_SEND_DTL.TENANT_ID            IS '테넌트 ID';

CREATE INDEX IDX_DTL_SEND_SEQ   ON ADM_EMAIL_SEND_DTL (EMAIL_SEND_SEQ);
CREATE INDEX IDX_DTL_STS_CD     ON ADM_EMAIL_SEND_DTL (SEND_STS_CD);
CREATE INDEX IDX_DTL_SES_MSG_ID ON ADM_EMAIL_SEND_DTL (SES_MSG_ID);

CREATE TABLE IF NOT EXISTS ADM_EMAIL_ATTCH_FILE_LST (
    EMAIL_ATTACH_FILE_SEQ BIGSERIAL    PRIMARY KEY,
    EMAIL_SEND_DTL_SEQ    BIGINT       NOT NULL,
    FILE_PATH             VARCHAR(500) NULL,
    FILE_NM               VARCHAR(255) NULL,
    ORGN_FILE_NM          VARCHAR(255) NULL,
    FILE_SZ               BIGINT       NULL,
    FOREIGN KEY (EMAIL_SEND_DTL_SEQ) REFERENCES ADM_EMAIL_SEND_DTL(EMAIL_SEND_DTL_SEQ)
);

COMMENT ON COLUMN ADM_EMAIL_ATTCH_FILE_LST.EMAIL_SEND_DTL_SEQ IS 'FK: ADM_EMAIL_SEND_DTL';
COMMENT ON COLUMN ADM_EMAIL_ATTCH_FILE_LST.FILE_PATH           IS '파일 경로';
COMMENT ON COLUMN ADM_EMAIL_ATTCH_FILE_LST.FILE_NM             IS '파일명';
COMMENT ON COLUMN ADM_EMAIL_ATTCH_FILE_LST.ORGN_FILE_NM        IS '원본 파일명';
COMMENT ON COLUMN ADM_EMAIL_ATTCH_FILE_LST.FILE_SZ             IS '파일 크기';

-- =============================================
-- Blacklist Table
-- =============================================

CREATE TABLE IF NOT EXISTS ADM_EMAIL_BL_MST (
    EMAIL_BL_SEQ          BIGSERIAL    PRIMARY KEY,
    EMAIL_ADDR            VARCHAR(255) NOT NULL,
    EMAIL_CUTOFF_TYP_CD   VARCHAR(10)  NULL,
    STM_FIR_REG_DT        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_FIR_REG_USER_ID   VARCHAR(50)  NULL,
    STM_LAST_UPD_DT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    STM_LAST_UPD_USER_ID  VARCHAR(50)  NULL,
    UNIQUE (EMAIL_ADDR)
);

COMMENT ON COLUMN ADM_EMAIL_BL_MST.EMAIL_ADDR          IS '차단 이메일 주소';
COMMENT ON COLUMN ADM_EMAIL_BL_MST.EMAIL_CUTOFF_TYP_CD IS '차단 유형 코드';

-- =============================================
-- Tenant Registry Table
-- =============================================

CREATE TABLE IF NOT EXISTS TENANT_REGISTRY (
    TENANT_ID            VARCHAR(36)  PRIMARY KEY,
    TENANT_NAME          VARCHAR(100) NOT NULL,
    SES_TENANT_NAME      VARCHAR(100) NULL,
    DOMAIN               VARCHAR(255) NOT NULL,
    API_KEY              VARCHAR(128) NOT NULL,
    CONFIG_SET_NAME      VARCHAR(100) NULL,
    VERIFICATION_STATUS  VARCHAR(20)  DEFAULT 'PENDING',
    QUOTA_DAILY          INT          DEFAULT 10000,
    QUOTA_MONTHLY        INT          DEFAULT 300000,
    STATUS               VARCHAR(20)  DEFAULT 'INACTIVE',
    CREATED_AT           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (DOMAIN),
    UNIQUE (API_KEY)
);

COMMENT ON COLUMN TENANT_REGISTRY.TENANT_NAME         IS '고객사 이름';
COMMENT ON COLUMN TENANT_REGISTRY.SES_TENANT_NAME     IS 'SES 테넌트 내부 명칭';
COMMENT ON COLUMN TENANT_REGISTRY.DOMAIN              IS '발송 도메인';
COMMENT ON COLUMN TENANT_REGISTRY.API_KEY             IS '테넌트별 API Key';
COMMENT ON COLUMN TENANT_REGISTRY.CONFIG_SET_NAME     IS 'SES Configuration Set 이름';
COMMENT ON COLUMN TENANT_REGISTRY.VERIFICATION_STATUS IS '도메인 인증 상태';
COMMENT ON COLUMN TENANT_REGISTRY.QUOTA_DAILY         IS '일일 발송 한도';
COMMENT ON COLUMN TENANT_REGISTRY.QUOTA_MONTHLY       IS '월간 발송 한도';
COMMENT ON COLUMN TENANT_REGISTRY.STATUS              IS '테넌트 상태';

CREATE INDEX IDX_STATUS ON TENANT_REGISTRY (STATUS);
