CREATE TABLE IF NOT EXISTS SUPPRESSION_LIST (
    ID BIGSERIAL PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    REASON VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (TENANT_ID, EMAIL)
);
CREATE INDEX IDX_SUPP_TENANT ON SUPPRESSION_LIST (TENANT_ID);
