CREATE TABLE IF NOT EXISTS TENANT_SENDER (
    ID         BIGSERIAL PRIMARY KEY,
    TENANT_ID  VARCHAR(36) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(100),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (TENANT_ID, EMAIL)
);

CREATE INDEX IDX_SENDER_TENANT ON TENANT_SENDER (TENANT_ID);
