-- 이메일 발송 배치 테이블 (JobDataMap 대체)
CREATE TABLE IF NOT EXISTS ADM_EMAIL_SEND_BATCH (
    BATCH_ID       VARCHAR(36) PRIMARY KEY,
    TEMPLATE_NAME  VARCHAR(255),
    FROM_ADDR      VARCHAR(255),
    TAGS           TEXT,           -- JSON array
    JOB_NAME       VARCHAR(255),
    JOB_GROUP      VARCHAR(255),
    DESCRIPTION    TEXT,
    START_DATE_AT  TIMESTAMP,
    STATUS         VARCHAR(30) DEFAULT 'PENDING',
    TOTAL_COUNT    INT DEFAULT 0,
    TENANT_ID      VARCHAR(50),
    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 이메일 발송 배치 항목 테이블 (개별 이메일)
CREATE TABLE IF NOT EXISTS ADM_EMAIL_SEND_BATCH_ITEM (
    ITEM_ID              BIGSERIAL PRIMARY KEY,
    BATCH_ID             VARCHAR(36) NOT NULL,
    ITEM_INDEX           INT NOT NULL,
    CORRELATION_ID       VARCHAR(36),
    EMAIL_SEND_DTL_SEQ   INT,          -- 폴링 경로용 (nullable)
    TO_ADDRS             TEXT NOT NULL, -- JSON array
    CC_ADDRS             TEXT,          -- JSON array
    BCC_ADDRS            TEXT,          -- JSON array
    TEMPLATE_PARAMETERS  TEXT,          -- JSON object
    CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ADM_BATCH FOREIGN KEY (BATCH_ID) REFERENCES ADM_EMAIL_SEND_BATCH(BATCH_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ADM_BATCH_ITEM_BATCH ON ADM_EMAIL_SEND_BATCH_ITEM(BATCH_ID, ITEM_INDEX);
