-- 템플릿-테넌트 매핑 테이블 (N:M 관계)
CREATE TABLE IF NOT EXISTS ADM_TEMPLATE_TENANT_MAP (
    MAP_SEQ          BIGSERIAL PRIMARY KEY,
    TEMPLATE_NAME    VARCHAR(255) NOT NULL,
    TENANT_ID        VARCHAR(100) NOT NULL,
    SUBJECT          TEXT,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_TEMPLATE_TENANT UNIQUE (TEMPLATE_NAME, TENANT_ID)
);

CREATE INDEX IDX_TEMPLATE_TENANT_NAME ON ADM_TEMPLATE_TENANT_MAP (TEMPLATE_NAME);
CREATE INDEX IDX_TEMPLATE_TENANT_ID ON ADM_TEMPLATE_TENANT_MAP (TENANT_ID);
