-- 배치 테이블에 tenant_id 컬럼 추가
ALTER TABLE ADM_EMAIL_SEND_BATCH ADD COLUMN IF NOT EXISTS TENANT_ID VARCHAR(50);

-- 템플릿-테넌트 매핑 테이블에 subject 컬럼 추가
ALTER TABLE ADM_TEMPLATE_TENANT_MAP ADD COLUMN IF NOT EXISTS SUBJECT TEXT;
