# Override Value

#################################################
# AWS {SES, DynamoDB}
#################################################
aws:
  dynamo:
    region: ap-northeast-2
    access-key: AKIA2F6HCY2MNDRHU6BX
    secret-key: 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
  ses:
    region: ap-northeast-2
    access-key: AKIA2F6HCY2MNDRHU6BX
    secret-key: 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

#################################################
# bot
#################################################
bot:
  telegram:
    token-id: 5710353844:AAFJeWE2TxtH05yIeSycwQ4Cj71Gm6qzodA
    channel-names: NFTReally.Notification, NFTReally.BackEnd, NFTReally.NTE, NFTReally.NTC, NFTReally.NTS, NFTReally.NBS, NFTReally.NBA, NFTReally.Deploy

#################################################
# polling checker
#################################################
polling:
  schedule:
    send-email-check-time: 60000
    send-email-event-check-time: 60000


