# Override Value

#################################################
# AWS {SES, DynamoDB}
#################################################
aws:
  dynamo:
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  ses:
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

#################################################
# bot
#################################################
bot:
  telegram:
    token-id: ${TELEGRAM_BOT_TOKEN}
    channel-names: NFTReally.Notification, NFTReally.BackEnd, NFTReally.NTE, NFTReally.NTC, NFTReally.NTS, NFTReally.NBS, NFTReally.NBA, NFTReally.Deploy

#################################################
# polling checker
#################################################
polling:
  schedule:
    send-email-check-time: 60000
    send-email-event-check-time: 60000


