# Dev58 profile overrides

management:
  endpoints:
    web:
      exposure:
        include: health,info,quartz
  endpoint:
    health:
      show-details: always

bot:
  telegram:
    channel-names: NFTReally.Notification, NFTReally.BackEnd, NFTReally.NTE, NFTReally.NTC, NFTReally.NTS, NFTReally.NBS, NFTReally.NBA
